float:
  any:
  - base_args: ['@metric']
    constructor: CUBVEC 
    disabled: false
    docker_tag: localhost/ann-benchmarks-cubrid
    module: ann_benchmarks.algorithms.cubrid
    name: cubrid
    run_groups:
      M-16:
        arg_groups: [{M: 16, efConstruction: 200}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 200}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
